/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "./asn1c/ASN1_files/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_CounterCheck_r8_IEs_H_
#define	_CounterCheck_r8_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRB-CountMSB-InfoList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CounterCheck_v8a0_IEs;

/* CounterCheck-r8-IEs */
typedef struct CounterCheck_r8_IEs {
	DRB_CountMSB_InfoList_t	 drb_CountMSB_InfoList;
	struct CounterCheck_v8a0_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CounterCheck_r8_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CounterCheck_r8_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CounterCheck-v8a0-IEs.h"

#endif	/* _CounterCheck_r8_IEs_H_ */
#include <asn_internal.h>
