/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "./asn1c/ASN1_files/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_P_Max_H_
#define	_P_Max_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* P-Max */
typedef long	 P_Max_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_P_Max;
asn_struct_free_f P_Max_free;
asn_struct_print_f P_Max_print;
asn_constr_check_f P_Max_constraint;
ber_type_decoder_f P_Max_decode_ber;
der_type_encoder_f P_Max_encode_der;
xer_type_decoder_f P_Max_decode_xer;
xer_type_encoder_f P_Max_encode_xer;
per_type_decoder_f P_Max_decode_uper;
per_type_encoder_f P_Max_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _P_Max_H_ */
#include <asn_internal.h>
