/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "./asn1c/ASN1_files/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_RNReconfiguration_r10_H_
#define	_RNReconfiguration_r10_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC-TransactionIdentifier.h"
#include "RNReconfiguration-r10-IEs.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RNReconfiguration_r10__criticalExtensions_PR {
	RNReconfiguration_r10__criticalExtensions_PR_NOTHING,	/* No components present */
	RNReconfiguration_r10__criticalExtensions_PR_c1,
	RNReconfiguration_r10__criticalExtensions_PR_criticalExtensionsFuture
} RNReconfiguration_r10__criticalExtensions_PR;
typedef enum RNReconfiguration_r10__criticalExtensions__c1_PR {
	RNReconfiguration_r10__criticalExtensions__c1_PR_NOTHING,	/* No components present */
	RNReconfiguration_r10__criticalExtensions__c1_PR_rnReconfiguration_r10,
	RNReconfiguration_r10__criticalExtensions__c1_PR_spare3,
	RNReconfiguration_r10__criticalExtensions__c1_PR_spare2,
	RNReconfiguration_r10__criticalExtensions__c1_PR_spare1
} RNReconfiguration_r10__criticalExtensions__c1_PR;

/* RNReconfiguration-r10 */
typedef struct RNReconfiguration_r10 {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct RNReconfiguration_r10__criticalExtensions {
		RNReconfiguration_r10__criticalExtensions_PR present;
		union RNReconfiguration_r10__criticalExtensions_u {
			struct RNReconfiguration_r10__criticalExtensions__c1 {
				RNReconfiguration_r10__criticalExtensions__c1_PR present;
				union RNReconfiguration_r10__criticalExtensions__c1_u {
					RNReconfiguration_r10_IEs_t	 rnReconfiguration_r10;
					NULL_t	 spare3;
					NULL_t	 spare2;
					NULL_t	 spare1;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} c1;
			struct RNReconfiguration_r10__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RNReconfiguration_r10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RNReconfiguration_r10;

#ifdef __cplusplus
}
#endif

#endif	/* _RNReconfiguration_r10_H_ */
#include <asn_internal.h>
