/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "./asn1c/ASN1_files/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_ULHandoverPreparationTransfer_r8_IEs_H_
#define	_ULHandoverPreparationTransfer_r8_IEs_H_


#include <liblte/rrc/asn/asn_application.h>

/* Including external dependencies */
#include "liblte/rrc/asn/CDMA2000-Type.h"
#include <liblte/rrc/asn/BIT_STRING.h>
#include "liblte/rrc/asn/DedicatedInfoCDMA2000.h"
#include <liblte/rrc/asn/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ULHandoverPreparationTransfer_v8a0_IEs;

/* ULHandoverPreparationTransfer-r8-IEs */
typedef struct ULHandoverPreparationTransfer_r8_IEs {
	CDMA2000_Type_t	 cdma2000_Type;
	BIT_STRING_t	*meid	/* OPTIONAL */;
	DedicatedInfoCDMA2000_t	 dedicatedInfo;
	struct ULHandoverPreparationTransfer_v8a0_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ULHandoverPreparationTransfer_r8_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ULHandoverPreparationTransfer_r8_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "liblte/rrc/asn/ULHandoverPreparationTransfer-v8a0-IEs.h"

#endif	/* _ULHandoverPreparationTransfer_r8_IEs_H_ */
#include <liblte/rrc/asn/asn_internal.h>
