/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 */

#ifndef	_SystemInformationBlockType1_H_
#define	_SystemInformationBlockType1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "P-Max.h"
#include <NativeInteger.h>
#include "SchedulingInfoList.h"
#include <NativeEnumerated.h>
#include "PLMN-IdentityList.h"
#include "TrackingAreaCode.h"
#include "CellIdentity.h"
#include <BOOLEAN.h>
#include "CSG-Identity.h"
#include <constr_SEQUENCE.h>
#include "Q-RxLevMin.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cellBarred {
	cellBarred_barred	= 0,
	cellBarred_notBarred	= 1
} e_cellBarred;
typedef enum intraFreqReselection {
	intraFreqReselection_allowed	= 0,
	intraFreqReselection_notAllowed	= 1
} e_intraFreqReselection;
typedef enum si_WindowLength {
	si_WindowLength_ms1	= 0,
	si_WindowLength_ms2	= 1,
	si_WindowLength_ms5	= 2,
	si_WindowLength_ms10	= 3,
	si_WindowLength_ms15	= 4,
	si_WindowLength_ms20	= 5,
	si_WindowLength_ms40	= 6
} e_si_WindowLength;

/* Forward declarations */
struct TDD_Config;
struct SystemInformationBlockType1_v890_IEs;

/* SystemInformationBlockType1 */
typedef struct SystemInformationBlockType1 {
	struct cellAccessRelatedInfo {
		PLMN_IdentityList_t	 plmn_IdentityList;
		TrackingAreaCode_t	 trackingAreaCode;
		CellIdentity_t	 cellIdentity;
		long	 cellBarred;
		long	 intraFreqReselection;
		BOOLEAN_t	 csg_Indication;
		CSG_Identity_t	*csg_Identity	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} cellAccessRelatedInfo;
	struct cellSelectionInfo {
		Q_RxLevMin_t	 q_RxLevMin;
		long	*q_RxLevMinOffset	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} cellSelectionInfo;
	P_Max_t	*p_Max	/* OPTIONAL */;
	long	 freqBandIndicator;
	SchedulingInfoList_t	 schedulingInfoList;
	struct TDD_Config	*tdd_Config	/* OPTIONAL */;
	long	 si_WindowLength;
	long	 systemInfoValueTag;
	struct SystemInformationBlockType1_v890_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformationBlockType1_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellBarred_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_intraFreqReselection_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_si_WindowLength_21;	// (Use -fall-defs-global to expose) */
LIBLTE_API extern asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TDD-Config.h"
#include "SystemInformationBlockType1-v890-IEs.h"

#endif	/* _SystemInformationBlockType1_H_ */
#include <asn_internal.h>
